[tool.taskipy.tasks]
image = { cmd = "docker build . --file Dockerfile --tag gabrielbdornas/speech-to-text:latest", help = "Build Docker image." }
container = { cmd = "docker run -it --rm gabrielbdornas/speech-to-text:latest bash", help = "Start Docker container." }
